### PR TITLE
Default file for gitlab ci runner

### PR DESCRIPTION
**Pull request by Wachiwi**
@jvanbaarsen New try of #98

What did I change:

* Added default file for init script to allow configuration for the
runner
* Updated install area inside ReadMe.md
* Adapted the indention of the switch-case to match the rest of the
script

**EDIT:**

* Fixed description of line 17
* Edited init.d-script variables to lowercase variables to match
default file

### CODE REVIEW

**Comment by Wachiwi** [comment]
@jvanbaarsen bump

**Comment by axilleas** [comment]
@Wachiwi it looks good. Can you rebase to latest master, since this is not mergeable at its current state. Thanks!

**Comment by Wachiwi** [comment]
@axilleas should be fine now.

btw are the commands below correct for general rebasing?

```
git checkout master 
git remote add original git@github.com:gitlabhq/gitlab-ci-runner.git
git fetch original
git status
git merge author/master
git checkout default_config
git rebase master
```

**Comment by axilleas** [comment]
Generally yes. You have two remotes, yours (let's say origin) and the gitlab one (let's say upstream).

I checkout to upstream and do a `git pull`, then checkout origin and do a `git rebase upstream`.

**Pull request merged**
